version: '3.4'

services:
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '127.0.0.1:6380:6379'
    volumes:
      - ./docker/Data/redis:/bitnami/redis/data
  erply_api:
    image: 'erply_api:latest'
    depends_on:
      - redis
    entrypoint: /app/erply_server
    ports:
      - 127.0.0.1:3001:3001
    restart: on-failure
