version: '3.4'

services:
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '127.0.0.1:6380:6379'
    volumes:
      - ./docker/Data/redis:/bitnami/redis/data
  erply_api:
    image: 'erply_api:latest'
    depends_on:
      - redis
      - erply_db
    entrypoint: /app/erply_server server
    ports:
      - 127.0.0.1:8082:8082
    restart: on-failure
    volumes:
      - ./apidoc:/app/apidoc
      - ./templates:/app/templates
      - ./favicon.ico:/app/favicon.ico
  erply_db:
    image: breathbath/mysql8
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: erply_db
    volumes:
      - ./docker/Data/erply_db:/var/lib/mysql
      - ./docker/mysqlConfServer.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysqlConfClient.cnf:/root/.my.cnf
    env_file:
      - ./docker/mysqlConfEnv.env
    ports:
      - 127.0.0.1:3310:3306
    restart: always
